version: '2.1'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  vault:
    image: hashicorp/vault:latest
    container_name: myvault
    ports:
      - "8200:8200"
    environment:
#     Set the ID of the generated root token. The root token is the initial access token to start configuring Vault
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
#     Set the IP address and port of the development server listener; the default value is 0.0.0.0:8200
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK